apiVersion: v1
kind: Pod
metadata:
  name: sleeper
spec:
  containers:
  - name: sleeper
    image: busybox
    command: [ command: ["/bin/bash", "-c", "while true ; do sleep 10 ; done"] ]
  restartPolicy: Never